### ISSUE TITLE
Indexed Maps

### ISSUE THREAD

**Issue by toastal** [yotamDvir/elm-pivot#2]
`indexedMapCLR` would be really nice right about now in my project. ...Or at least an easy way to zip a tuple of `( Int, a )`.

**Comment by yotamDvir** [comment]
Figured someone would ask for this eventually. The best solution I came up with is to expose a function

```elm
indexed : (Pivot (Int, a) -> Pivot b) -> Pivot a -> Pivot b
```

With this function all maps can be made indexed maps without much overhead

```elm
indexedMapCLR == mapCLR fc fl fr |> withIndices
-- where `fc` `fl` `fr` are of type `(Int, a) -> b`.
```

Implementing zip is even simpler

```elm
zip == indexed identity
```

**Comment by yotamDvir** [comment]
Added `zip` in version 1.1.0.
